--- Makefile.orig	2011-12-22 10:59:08.000000000 -0800
+++ Makefile	2011-12-22 10:59:08.000000000 -0800
@@ -19,6 +19,7 @@
 # $Id: Makefile,v 1.10 2007-09-23 19:22:24 ian Exp $
 
 prefix=/usr/local
+#prefix=/Users/tj/local/authbind
 
 bin_dir=$(prefix)/bin
 lib_dir=$(prefix)/lib/authbind
@@ -30,62 +31,85 @@
 man8_dir=$(man_dir)/man8
 
 etc_dir=/etc/authbind
+#etc_dir=/Users/tj/local/authbind/etc/authbind
 
-INSTALL_FILE	?= install -o root -g root -m 644 
-INSTALL_PROGRAM ?= install -o root -g root -m 755 -s
-INSTALL_DIR	?= install -o root -g root -m 755 -d
+INSTALL_USER=root
+INSTALL_GROUP=wheel
+#INSTALL_USER=tj
+#INSTALL_GROUP=staff
+
+INSTALL_FILE	?= install -o $(INSTALL_USER) -g $(INSTALL_GROUP) -m 644 
+INSTALL_PROGRAM ?= install -o $(INSTALL_USER) -g $(INSTALL_GROUP) -m 755 -s
+INSTALL_DIR	?= install -o $(INSTALL_USER) -g $(INSTALL_GROUP) -m 755 -d
 STRIP		?= strip
 
-OPTIMISE=	-O2
-LDFLAGS=	-g
-LIBS=		-ldl -lc
-CFLAGS=		-g $(OPTIMISE) \
-		-Wall -Wwrite-strings -Wpointer-arith -Wimplicit \
-		-Wnested-externs -Wmissing-prototypes -Wstrict-prototypes
-CPPFLAGS=	-DMAJOR_VER='"$(MAJOR)"' -DMINOR_VER='"$(MINOR)"' \
-		-DLIBAUTHBIND='"$(lib_dir)/$(LIBCANON)"' \
-		-DHELPER='"$(libexec_dir)/$(HELPER)"' -DCONFIGDIR='"$(etc_dir)"' \
-		-D_GNU_SOURCE
-
-MAJOR=1
-MINOR=0
-LIBCANON=	libauthbind.so.$(MAJOR)
-LIBTARGET=	$(LIBCANON).$(MINOR)
-BINTARGETS=	authbind
-HELPER=		helper
-
-TARGETS=		$(BINTARGETS) $(HELPER) $(LIBTARGET)
-MANPAGES_1=		authbind.1
-MANPAGES_8=		authbind-helper.8
-
-all:			$(TARGETS)
-
-install:		$(TARGETS)
-		$(INSTALL_DIR) $(lib_dir) $(man1_dir) $(man8_dir)
-		$(INSTALL_PROGRAM) $(BINTARGETS) $(bin_dir)/.
-		$(INSTALL_FILE) $(LIBTARGET) $(lib_dir)/.
-		$(STRIP) --strip-unneeded $(lib_dir)/$(LIBTARGET)
-		ln -sf $(LIBTARGET) $(lib_dir)/$(LIBCANON)
-		$(INSTALL_PROGRAM) $(HELPER) $(libexec_dir)/.
-		chmod u+s $(libexec_dir)/$(HELPER)
-		$(INSTALL_DIR) $(etc_dir) \
-			$(etc_dir)/byport $(etc_dir)/byaddr $(etc_dir)/byuid
-
-install_man:		$(MANPAGES_1) $(MANPAGES_8)
-		$(INSTALL_FILE) $(MANPAGES_1) $(man1_dir)/.
-		$(INSTALL_FILE) $(MANPAGES_8) $(man8_dir)/.
-
-libauthbind.o:		libauthbind.c authbind.h
-		$(CC) -D_REENTRANT $(CFLAGS) $(CPPFLAGS) -c -o $@ -fPIC $<
+# Note that it's necessary to build for both architectures, in order to
+# interoperate with executables of either arch.  For example, the Mac OSX
+# Android SDK provides i386 executables, which will fail from dyld failures
+# from loading the libauthbind.dylib library if that library is only built
+# for e.g. the x86_64 arch.
+ARCH=-arch i386 -arch x86_64
+OSX_CFLAGS=-flat_namespace
+OSX_LDFLAGS=$(ARCH) -dynamiclib -dynamic -flat_namespace
+
+OPTIMISE=-O2
+LDFLAGS=$(OSX_LDFLAGS)
+LIBS=-ldl
+CFLAGS=$(ARCH) -g $(OPTIMISE) -D_REENTRANT \
+ -Wall -Wwrite-strings -Wpointer-arith -Wimplicit -Wnested-externs \
+ -Wmissing-prototypes -Wstrict-prototypes $(OSX_CFLAGS)
+
+CPPFLAGS=-DMAJOR_VER='"$(MAJOR)"' \
+ -DMINOR_VER='"$(MINOR)"' \
+ -DLIBAUTHBIND='"$(lib_dir)/$(LIBRARY)$(LIBEXT)"' \
+ -DHELPER='"$(libexec_dir)/helper"' \
+ -DCONFIGDIR='"$(etc_dir)"' \
+ -D_GNU_SOURCE \
+ -DPRELOAD_VAR='"DYLD_INSERT_LIBRARIES"'
+
+LIBRARY=libauthbind
+LIBEXT=.dylib
+EXES=authbind helper
+OBJS=authbind.o helper.o
+
+TARGETS=$(EXES) $(LIBRARY)
+
+MANPAGES_1=authbind.1
+MANPAGES_8=authbind-helper.8
+
+all: $(TARGETS)
+
+install: $(TARGETS) install-man
+	mkdir -p $(bin_dir)
+	$(INSTALL_PROGRAM) authbind $(bin_dir)/.
+	chmod a+x $(bin_dir)/authbind
+	mkdir -p $(libexec_dir)
+	$(INSTALL_PROGRAM) helper $(libexec_dir)/.
+	chmod u+s $(libexec_dir)/helper
+	mkdir -p $(lib_dir)
+	$(INSTALL_FILE) $(LIBRARY)$(LIBEXT) $(lib_dir)/.
+#	$(STRIP) --strip-unneeded $(lib_dir)/$(LIBTARGET)
+#	ln -sf $(LIBTARGET) $(lib_dir)/$(LIBCANON)
+	$(INSTALL_DIR) $(etc_dir) $(etc_dir)/byport $(etc_dir)/byaddr $(etc_dir)/byuid
+
+install-man: $(MANPAGES_1) $(MANPAGES_8)
+	$(INSTALL_DIR) $(man1_dir) $(man8_dir)
+	$(INSTALL_FILE) $(MANPAGES_1) $(man1_dir)/.
+	$(INSTALL_FILE) $(MANPAGES_8) $(man8_dir)/.
+
+.c.o:
+	$(CC) $(CPPFLAGS) $(CFLAGS) -c $<
 
-authbind:		authbind.o
-helper:			helper.o
+authbind: authbind.o
+	$(CC) -o $@ $<
 
-helper.o authbind.o:	authbind.h
+helper: helper.o
+	$(CC) -o $@ $<
 
-$(LIBTARGET):		libauthbind.o
-		ld -shared -soname $(LIBCANON) -o $@ $< $(LIBS)
+$(LIBRARY):
+	$(CC) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -o $@$(LIBEXT) $@.c $(LIBS)
 
 clean distclean:
-		rm -f $(TARGETS) *.o *~ ./#*# *.bak *.new core
-		rm -f libauthbind.so* *.core
+	$(RM) $(TARGETS) *.o *~ ./#*# *.bak *.new core
+	$(RM) $(LIBRARY)$(LIBEXT) *.core
+	$(RM) -r $(LIBRARY)$(LIBEXT).dSYM/
